node_js:
  - 0.12
  - 0.10
script:
- npm test
- npm run coverrage
addons:
   code_climate:
   repo_token: 2c649d2c03f0a397f5fb843024798c0ff07030cbeb78c49d5ca30511a49a94cb
after_script:
- npm run code_climate
